# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Socket-Multicast
version:      0.01
version_from: lib/Socket/Multicast.pm
installdirs:  site
requires:
    ExtUtils::Constant:            0
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
